CREATE TABLE IF NOT EXISTS banks(
    bank_code INT NOT NULL,
    bank_name VARCHAR(47),
    PRIMARY KEY (bank_code)
);

INSERT INTO banks VALUES
    (7010,'Bank of Ceylon'),
    (7038,'Standard Chartered Bank'),
    (7047,'Citi Bank'),
    (7056,'Commercial Bank PLC'),
    (7074,'Habib Bank Ltd'),
    (7083,'Hatton National Bank PLC'),
    (7092,'Hongkong Shanghai Bank'),
    (7108,'Indian Bank'),
    (7117,'Indian Overseas Bank'),
    (7135,'Peoples Bank'),
    (7144,'state bank of india'),
    (7162,'nations trust bank PLC'),
    (7205,'deutsche bank'),
    (7214,'National Development Bank PLC'),
    (7269,'MCB bank ltd'),
    (7278,'sampath bank PLC'),
    (7287,'seylan bank PLC'),
    (7302,'union bank of Colombo PLC'),
    (7311,'Pan Asia Banking Corporation PLC'),
    (7454,'DFCC Bank PLC'),
    (7463,'Amana Bank PLC'),
    (7481,'Cargills Bank Limited'),
    (7612,'Cooperative Regional Rural Bank LTD Polgahawela'),
    (7658,'Lanka Credit and Business Finance Limited'),
    (7719,'National Savings Bank'),
    (7728,'Sanasa Development Bank'),
    (7737,'HDFC Bank'),
    (7746,'Citizen Development Business Finance PLC'),
    (7755,'Regional Development Bank'),
    (7764,'State Mortgage & Investment Bank'),
    (7773,'LB Finance PLC'),
    (7782,'Senkadagala Finance PLC'),
    (7807,'Commercial Leasing & Finance'),
    (7816,'Vallibel Finance PLC'),
    (7825,'Central Finance PLC'),
    (7834,'Kanrich Finance Limited'),
    (7852,'Alliance Finance Company PLC'),
    (7861,'LOLC Finance PLC '),
    (7898,'Merchant Bank of Sri Lanka & Finance PLC'),
    (7904,'HNB Finance PLC'),
    (7913,'Mercantile Investment and Finance PLC '),
    (7922,'People''s Leasing & Finance PLC'),
    (7968,'Siyapatha Finanace PLC'),
    (7959,'Bimputh Finance PLC');
